AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fluidity CA Lambda - Certificate Authority Service for Dynamic Certificate Generation'

Parameters:
  StackName:
    Type: String
    Default: fluidity-ca
    Description: Stack name for CA Lambda resources
  
  CASecretName:
    Type: String
    Default: fluidity/ca-certificate
    Description: Name of the secret in AWS Secrets Manager containing CA certificate and key

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Configuration"
        Parameters:
          - StackName
          - CASecretName

Resources:
  # IAM Role for CA Lambda
  CALambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CASecretName}-*'

  # CA Lambda Function
  CALambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${StackName}-signer'
      Runtime: go1.x
      Handler: bootstrap
      Role: !GetAtt CALambdaExecutionRole.Arn
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          CA_SECRET_NAME: !Ref CASecretName
      Code:
        # This should be replaced with actual deployment package
        ZipFile: |
          # Placeholder - actual code will be deployed via build process
          echo "CA Lambda function placeholder"

  # API Gateway for CA Lambda
  CALambdaAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${StackName}-api'
      Description: 'Fluidity CA Certificate Signing API'
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Resource for CSR endpoint
  CSRResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref CALambdaAPI
      ParentId: !GetAtt CALambdaAPI.RootResourceId
      PathPart: sign

  # API Method - POST /sign
  CSRMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref CALambdaAPI
      ResourceId: !Ref CSRResource
      HttpMethod: POST
      AuthorizationType: AWS_IAM
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CALambda.Arn}/invocations'

  # Lambda permission for API Gateway
  CALambdaAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CALambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CALambdaAPI}/*'

  # API Deployment
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - CSRMethod
    Properties:
      RestApiId: !Ref CALambdaAPI
      StageName: prod

  # CloudWatch Log Group for CA Lambda
  CALambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${CALambda}'
      RetentionInDays: 14

  # CloudWatch Alarms
  CALambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${StackName}-errors'
      AlarmDescription: 'Alert when CA Lambda has errors'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CALambda
      TreatMissingData: notBreaching

  CALambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${StackName}-high-duration'
      AlarmDescription: 'Alert when CA Lambda has high execution time'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CALambda
      TreatMissingData: notBreaching

Outputs:
  CALambdaArn:
    Description: ARN of the CA Lambda function
    Value: !GetAtt CALambda.Arn
    Export:
      Name: !Sub '${StackName}-lambda-arn'

  CALambdaName:
    Description: Name of the CA Lambda function
    Value: !Ref CALambda
    Export:
      Name: !Sub '${StackName}-lambda-name'

  CAAPIEndpoint:
    Description: CA Certificate Signing API endpoint URL
    Value: !Sub 'https://${CALambdaAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/sign'
    Export:
      Name: !Sub '${StackName}-api-endpoint'

  CASecretArn:
    Description: ARN of the CA certificate secret
    Value: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CASecretName}'
